stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"
    - ls
    - ./gradlew build -x test

job_test:
  stage: test
  script:
    - echo "Running tests"
    - ./gradlew build test
